---
title: "applyFunctionsetal"
author: "Kishore Hari"
date: "2022-10-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Automation

Write a function that will extract all the numeric columns and plot a histogram for each numeric column and save the plot as an image.
```{r}
library(nycflights13)
df <- flights
hist_num_col <- function(df) {
   df1 <- df %>% select(is.numeric)
    df1 %>% ggplot(aes(x = air_time)) + geom_histogram()
    
    for (i in 1:ncol(df1)) {
        p <- df1 %>% ggplot(aes_string(x = colnames(df1)[i])) +
            geom_histogram()
        ggsave(paste0(colnames(df1)[i], ".png"), width = 5, height = 5)
    } 
}

```

Write a function that plots histograms an barplots using appropriate variables
in a dataframe

```{r}
histsNbars <- function(df) {
    df1 <- df %>% select(is.numeric)
    for (i in colnames(df1)) {
        ggplot(df1, aes_string(x = i)) +
            geom_histogram()
        ggsave(paste0(i, ".png"), width = 5, height = 5)
    }
    df1 <- df %>% select(is.character)
    for (i in colnames(df1)) {
        ggplot(df1, aes_string(x = i)) +
            geom_bar()
        ggsave(paste0(i, ".png"), width = 5, height = 5)
     }
}
histsNbars(fligths)
```


